In [1]:
import numpy as np


In [2]:
a = np. array([1,2,3,4,5,6])

In [3]:
a

array([1, 2, 3, 4, 5, 6])

In [4]:
a[0]

1

In [6]:
a[:2]

array([1, 2])

In [8]:
a[2:5]

array([3, 4, 5])

In [10]:
a[1:-2]

array([2, 3, 4])

In [11]:
a[0:5:2]

array([1, 3, 5])

In [12]:
a[0]=100

In [14]:
b = a[0:-1]

In [15]:
b[-1]=101
b

array([100,   2,   3,   4, 101])

In [17]:
c =np.array([[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3],[4,4,4,4,4]])

In [18]:
c[2:5]

array([[3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [21]:
c[1][1:3]

array([2, 2])

In [28]:
c[1:4, 0:2]

array([[2, 2],
       [3, 3],
       [4, 4]])

In [ ]:

print(a.dtype, b.dtype, c.dtype)

a.dtype b.dtype c.dtype
int32 int32 int32


In [32]:
c[1:4, 0:2] = 0

In [33]:
c

array([[1, 1, 1, 1, 1],
       [0, 0, 2, 2, 2],
       [0, 0, 3, 3, 3],
       [0, 0, 4, 4, 4]])

In [34]:
c[0]

array([1, 1, 1, 1, 1])

In [44]:
c[0:-1, 3:5]=21

In [45]:
c

array([[ 1,  1,  1, 21, 21],
       [ 0,  0,  2, 21, 21],
       [ 0,  0,  3, 21, 21],
       [ 0,  0,  4,  4,  4]])

In [50]:
print(a.ndim,
b.ndim,
c.ndim)

1 1 2


In [51]:
print(a.shape,b.shape, c.shape)

(6,) (5,) (4, 5)


In [52]:
c.size

20

In [55]:
import math
a.size == math.prod(a.shape)


True

In [56]:
#HOW TO CREATE BASIC ARRAYS

np.zeros([2,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [57]:
np.ones([5,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [61]:
np.empty([2,2])

array([[2.12199579e-314, 1.34746733e-311],
       [3.10273226e-321, 3.79442416e-321]])

In [62]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np.arange(1,10,3)

array([1, 4, 7])

In [71]:
np.arange(0,101,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [76]:
np.linspace(0,100,num=5)

array([  0.,  25.,  50.,  75., 100.])

In [78]:
x = np.linspace(2,10, num=3, dtype=np.int64)
x

array([ 2,  6, 10], dtype=int64)

In [85]:
y= np.random.rand(3,4)
y

array([[0.46749629, 0.89742362, 0.23668752, 0.30287225],
       [0.74388595, 0.67434869, 0.86463809, 0.79574081],
       [0.66316673, 0.19834982, 0.63803964, 0.95714719]])

In [86]:
np.sort(y)

array([[0.23668752, 0.30287225, 0.46749629, 0.89742362],
       [0.67434869, 0.74388595, 0.79574081, 0.86463809],
       [0.19834982, 0.63803964, 0.66316673, 0.95714719]])

In [88]:
np.sort(y, axis=0)


array([[0.46749629, 0.19834982, 0.23668752, 0.30287225],
       [0.66316673, 0.67434869, 0.63803964, 0.79574081],
       [0.74388595, 0.89742362, 0.86463809, 0.95714719]])

In [104]:
a = np.arange(1,10, 3)
b= np.linspace(1,9, num=3)
a, b

(array([1, 4, 7]), array([1., 5., 9.]))

In [105]:
q = np.concatenate((a,b))

In [106]:
q

array([1., 4., 7., 1., 5., 9.])

In [108]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
n = np.array([[10,11,12],[13,14,15],[16,17,18]])

In [109]:
m, n

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]))

In [111]:
list = [m,n]
list

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])]

In [116]:
l = np.concatenate((m,n), axis=0)
l

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [119]:
l2 = np.concatenate((m,n), axis=1)
l2

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [121]:
l2.shape

(3, 6)

In [122]:
l2.ndim

2

In [124]:
l.size

18

In [126]:
l2.reshape(3,6)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [131]:
np.reshape(l,(6,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
#HOW TO CONVERT 1D ARRAY INTO 2D ARRAY

